dependencies:
  - conda-forge::numpy=2.1.2
  - conda-forge::pip=24.0
  - conda-forge::python=3.12
  - conda-forge::scipy=1.14.1
  - pytorch::pytorch=2.5.1
  - pip:
      - matplotlib==3.9.2
      - sbi==0.23.2
      - git+https://github.com/jan-rybizki/Chempy.git
